WebPlatformForEmbedded/meta-wpe

recipes-multimedia/gstreamer/gstreamer1.0-plugins-base-1.6.1/0002-appsrc-duration-query-support-based-on-the-size-prop.patch
recipes-multimedia/gstreamer/gstreamer1.0-plugins-base_1.6.1.bbappend
recipes-wpe/wpe/wpe_0.1.bb

a2d7d8c Build fix for punch hole after the latest pull from upstream
Signed-off-by: Andre McCurdy <armccurdy@gmail.com>

wpe: update SRCREV

---

recipes-wpe/wpe/wpe_0.1.bb

this helps in overriding the WPE repos that folks could have forked
via a bbappend

wpe: Allow overrides for wpe SRC_URI

---

recipes-graphics/cairo/cairo/0006-add-egl-device-create.patch
recipes-graphics/cairo/cairo_%.bbappend

cairo: Add cairo_egl_device_create_for_egl_surface API

---

recipes-multimedia/gstreamer/gstreamer1.0-1.6.2/0001-typefind-min-1k.patch
recipes-multimedia/gstreamer/gstreamer1.0-1.6.2/0002-queue2-Add-the-avg-in-rate-property.patch
recipes-multimedia/gstreamer/gstreamer1.0-1.6.2/0003-bin-implement-context-propagation-when-adding-elements.patch
recipes-multimedia/gstreamer/gstreamer1.0-1.6.2/0004-queue2-add-overrun-signal.patch
recipes-multimedia/gstreamer/gstreamer1.0-plugins-bad-1.6.2/0002-mssdemux-PlayReady-WRM-parsing-support.patch
recipes-multimedia/gstreamer/gstreamer1.0-plugins-bad-1.6.2/0003-adaptivedemux-improved-bitrate-estimations.patch
recipes-multimedia/gstreamer/gstreamer1.0-plugins-bad-1.6.2/0004-mssdemux-improved-live-playback-support.patch
recipes-multimedia/gstreamer/gstreamer1.0-plugins-bad-1.6.2/0006-daptivedemux-minimal-HTTP-context-support.patch
recipes-multimedia/gstreamer/gstreamer1.0-plugins-bad-1.6.2/0007-optimize-gl-rpi-wip.patch
recipes-multimedia/gstreamer/gstreamer1.0-plugins-bad_1.6.2.bbappend
recipes-multimedia/gstreamer/gstreamer1.0-plugins-base-1.6.2/0001-Revert-uridecodebin-Use-the-correct-caps-name-for-MS.patch
recipes-multimedia/gstreamer/gstreamer1.0-plugins-base-1.6.2/0002-appsrc-duration-query-support-based-on-the-size-prop.patch
recipes-multimedia/gstreamer/gstreamer1.0-plugins-base_1.6.2.bbappend
recipes-multimedia/gstreamer/gstreamer1.0-plugins-good-1.6.2/0002-qtdemux-PIFF-box-detection-and-minimal-parsing-suppo.patch
recipes-multimedia/gstreamer/gstreamer1.0-plugins-good-1.6.2/0003-qtdemux-read-saio-aux_info_type-as-a-FOURCC.patch
recipes-multimedia/gstreamer/gstreamer1.0-plugins-good-1.6.2/0004-Use-the-tfdt-decode-time-when-it-s-significantly-dif.patch
recipes-multimedia/gstreamer/gstreamer1.0-plugins-good-1.6.2/0005-souphttpsrc-cookie-jar-and-context-query-support.patch
recipes-multimedia/gstreamer/gstreamer1.0-plugins-good_1.6.2.bbappend
recipes-multimedia/gstreamer/gstreamer1.0_1.6.2.bbappend

This reverts commit 9e8e1b72abda6a9eecf3d2006b5f119c75e2df57.

Bring back the Gstreamer 1.6.2 recipes and patches

---

recipes-wpe/wpe/wpe_0.1.bb

wpe: Bump to latest

---

recipes-middleware/cppsdk/cppsdk_git.bb

cppsdk: Bump to latest

---

conf/layer.conf
recipes-multimedia/gstreamer/gstreamer1.0-plugins-bad_%.bbappend
recipes-wpe/wpe/wpe_0.1.bb

rpi: Add gstreamer1.0-omx and gstreamer1.0-plugins-bad-opengl

---

recipes-wpe/wpe/wpe_0.1.bb

wpe: Bump to get build with Westeros backend

---

recipes-core/images/wpe-image.inc

make the image truly opensource with WPE+wersteros

wpe-image: Remove metro middleware

---

recipes-wpe/wpe/wpe_0.1.bb

Ensure that fontconfig's default search path contains some fonts.

wpe: add ttf-bitstream-vera to RRECOMMENDS

---

recipes-graphics/westeros/westeros.inc

The real fix is here
https://code.rdkcentral.com/r/#/c/6095/
Its still being vetted until then apply
this workaround to achieve same effect

westeros-sink: link with westeros compositor

---

recipes-graphics/westeros-soc/westeros-sink.bbappend
recipes-graphics/westeros-soc/westeros-soc-drm.bb
recipes-graphics/westeros/westeros.bb
recipes-graphics/westeros/westeros.bbappend

Changes for adding drm support to westeros and enabling it on hikey-32 machine

westeros: adding drm support

---

recipes-graphics/westeros-soc/westeros-soc-rpi.bb

westeros-soc-rpi: Ignore it for non-pi SoCs

---

COPYING.MIT
LICENSE

Add MIT license information

---

recipes-graphics/westeros-soc/westeros-sink.bbappend

Enabling gst1 as gst1 dependency is added to westeros and updating license location for hikey also

westeros-sink: enabling gst1 and license for hikey

---

recipes-graphics/westeros-soc/westeros-sink.bbappend
recipes-graphics/westeros-soc/westeros-soc-drm.bb
recipes-graphics/westeros/westeros.bb
recipes-graphics/westeros/westeros.bbappend

Added changes for westeros to work on dragonboard-410c-32 machine.

westeros: support for DB410c target

---

recipes-graphics/westeros/westeros.inc

Fix build with recently OE master which uses per-recipe
sysroots

westeros: Update to latest

---

recipes-wpe/wpe/wpe_0.1.bb

Option to enable/disable subtitle and native video in webkitmediaplayer

wpe: option for subtitle & native video

---

recipes-graphics/westeros-soc/westeros-sink.bbappend
recipes-graphics/westeros-soc/westeros-soc-drm.bb
recipes-graphics/westeros/westeros.bb
recipes-graphics/westeros/westeros.bbappend
recipes-wpe/wpewebkit/wpewebkit_0.1.bb

Signed-off-by: Pramod Gurav <pramod.gurav@linaro.org>

db820c: westeros support for db820c 32 bit

---

recipes-graphics/cairo/cairo_%.bbappend

cairo: Add egl glesv2 only if x11 is not in distro features

---

recipes-graphics/harfbuzz/harfbuzz_1.0.1.bb

Signed-off-by: sivasubramanian <psiva87@gmail.com>

Fixing incorrect icu configure flag

---

recipes-wpe/wpewebkit/files/0001-mse-Print-MediaTime-consistently-using-s.patch
recipes-wpe/wpewebkit/wpewebkit_20170728.bb

wpewebkit: Partial backport a fix for compiler error with clang

---

recipes-wpe/wpewebkit/files/0001-Fix-build-with-musl.patch
recipes-wpe/wpewebkit/wpewebkit_20170728.bb

wpewebkit: Fix build with musl

---

recipes-wpe/wpewebkit/files/0001-Define-MESA_EGL_NO_X11_HEADERS-when-not-using-GLX.patch
recipes-wpe/wpewebkit/wpewebkit_20170728.bb

wpewebkit: Fix build with mali graphics drivers

---

recipes-graphics/westeros/westeros-render-dispmanx.bb

westeros-render-dispmanx: Keep it just for rpi hosts

---

recipes-graphics/westeros/westeros-soc-drm.bb
recipes-graphics/westeros/westeros.bb

Westeros Compositor support on iMX8 64bit machine using DRM

Westeros support on iMX8

---

recipes-wpe/wpeframework/wpeframework-ocdm-playready_git.bb

Cherry picked from https://github.com/WebPlatformForEmbedded/meta-wpe/blob/8e2835285d1f980457e4d0aee86937da7f9c3295/recipes-wpe/wpeframework/wpeframework-ocdm-playready_git.bb

wpeframework-ocdm-playready: add recipe for Morty

---

recipes-graphics/libepoxy/libepoxy/0001-Make-graphic-libs-configurable.patch
recipes-graphics/libepoxy/libepoxy_%.bbappend
recipes-wpe/wpeframework/wpeframework-ocdm-clearkey_git.bb
recipes-wpe/wpeframework/wpeframework-ocdm-playready-nexus_git.bb
recipes-wpe/wpeframework/wpeframework-ocdm-playready_git.bb
recipes-wpe/wpeframework/wpeframework-ocdm-widevine_git.bb
recipes-wpe/wpeframework/wpeframework-plugins_git.bb
recipes-wpe/wpeframework/wpeframework-ui_git.bb
recipes-wpe/wpeframework/wpeframework_git.bb

Latest WPEFramework and WebKit components, tested on RPI3
Fixes issue with latest upstream libepoxy, as reported here https://github.com/Comcast/rdk-on-raspberrypi/issues/4

wpeframework bump to latest and libepoxy fix

---

recipes-graphics/westeros/westeros-soc-drm.bb
recipes-graphics/westeros/westeros.bb
recipes-graphics/westeros/westeros.bbappend

- multilib support for imx8m
- libdir name change in init script for Hikey 64bit

westeros multilib support for imx8m

---

recipes-wpe/wpeframework/wpeframework-ocdm-widevine-nexus-svp_git.bb
recipes-wpe/wpeframework/wpeframework-plugins_git.bb

wpeframework-ocdm-widevine-nexus-svp: initial checkin

---

recipes-wpe/wpewebkit/wpewebkit.inc

Separating out westeros-sink so that platforms w/o westeros-sink can override it if required. Like for glimagesink vsink, override it with egl.

wpewebkit: Support for other vsink on Westeros

---

recipes-devtools/cmake/cmake-native_3.7.2.bb
recipes-devtools/cmake/cmake.inc
recipes-devtools/cmake/cmake/0001-KWIML-tests-Remove-format-security-from-flags.patch
recipes-devtools/cmake/cmake/OEToolchainConfig.cmake
recipes-devtools/cmake/cmake/avoid-gcc-warnings-with-Wstrict-prototypes.patch
recipes-devtools/cmake/cmake/cmlibarchive-disable-ext2fs.patch
recipes-devtools/cmake/cmake/environment.d-cmake.sh
recipes-devtools/cmake/cmake/qt4-fail-silent.patch
recipes-devtools/cmake/cmake/support-oe-qt4-tools-names.patch
recipes-devtools/cmake/cmake_3.7.2.bb
recipes-support/icu/icu.inc
recipes-support/icu/icu/0001-Disable-LDFLAGSICUDT-for-Linux.patch
recipes-support/icu/icu/0001-i18n-Drop-include-xlocale.h.patch
recipes-support/icu/icu/fix-install-manx.patch
recipes-support/icu/icu/icu-pkgdata-large-cmd.patch
recipes-support/icu/icu_%.bbappend
recipes-support/icu/icu_57%.bbappend
recipes-support/icu/icu_58.2.bb
recipes-wpe/wpeframework/wpeframework-plugin-launcher_git.bb
recipes-wpe/wpeframework/wpeframework-plugins_git.bb
recipes-wpe/wpeframework/wpeframework.inc
recipes-wpe/wpeframework/wpeframework_git.bb
recipes-wpe/wpewebkit/wpewebkit.inc

- Bump to latest wpeframework
- Fix wpewebkit ocdm distro switch
- Add plugin launcher recipe

Morty updates

---

recipes-graphics/cairo/cairo/0001-add-noaa-compositor-for-v1.16.patch
recipes-graphics/cairo/cairo_%.bbappend
recipes-graphics/cairo/cairo_1.16.0.bbappend

Closes #282 , unsure if you want to support older cairo versions still. It was unclear which version the patch originally was applied to.

fix for cairo 1.16

---

recipes-wpe/wpeframework/wpeframework-plugin-launcher_git.bb

fatal: Unable to look up git@github.com (port 9418)
(Name or service not known)

Need this change to avoid fetch issues

---

recipes-graphics/westeros/westeros.inc

Need to change md5 checksum to fix fetch issues with westeos

---

recipes-wpe/wpeframework/wpeframework-ui_git.bb

Need to point SRCREV for wpeframework-UI to Spark Release

---

recipes-wpe/wpebackend-rdk/wpebackend-rdk_0.1.bb
recipes-wpe/wpeframework/wpeframework-plugins_git.bb

1) Browser window is rendered in small resolution
2) Key events are not working
Signed-off-by: rkhan467 <Riyaz.l@ltts.com>

Enabling wpeframework backend and compositor plugin to resolve below issues on Rpi

---

recipes-graphics/westeros/westeros-soc-drm.bb
recipes-graphics/westeros/westeros.bb

to avoid including it from other layer when present.

westeros: fix westeros.inc path

---

recipes-support/rdksplash/rdk-splash-ui_git.bb

Recipe to get RDK-Splash UI to images

---

recipes-wpe/wpeframework/wpeframework_git.bb

- test app package configuration
- gtest dependency
Signed-off-by: Moorthy Baskar <moorthy.baskaravenkatraman-sambamoorthy@linaro.org>

wpeframework: enabled test apps through PACKAGECONFIG

---

conf/layer.conf

layer.conf: Mark compatible with zeus release

---

recipes-core/images/wpe-eglfs-image.bb
recipes-core/images/wpe-westeros-image.bb
recipes-wpe/wpeframework/wpeframework-ocdm-playready_git.bb
recipes-wpe/wpeframework/wpeframework-ocdm-widevine_git.bb

distro_features_check is now deprecated

recipes: Use features_check instead of distro_features_check

---

recipes-wpe/wpeframework/wpeframework-ocdm-clearkey/0001-OpenSSL-align-implementation-with-latest-OpenSSL-1.1.patch

Signed-off-by: Moorthy Baskar <moorthy.baskaravenkatraman-sambamoorthy@linaro.org>

wpeframework-ocdm-clearkey: rebased openssl 1.1 patch

---

recipes-multimedia/gstreamer/gstreamer1.0-plugins-base_%.bbappend
recipes-multimedia/gstreamer/gstreamer1.0-plugins-good_%.bbappend
recipes-wpe/wpeframework/wpeframework/0004-StubGenerator-Python2-Python3-conversion.patch

gstreamer1.0-plugins-good: changes for meson based build.
wpeframework: Rebasing StubGenerator.py for Python2 to Python3 conversion.
Signed-off-by: Balaji Velmurugan <balaji.velmurugan@ltts.com>

gstreamer1.0-plugins-base: changes for meson based build.

---

recipes-graphics/noto-fonts/noto-fonts.bb

Support for arabic bengali chinese ethiopic georgian hebrew japanese korean thai languages

Language supports added

---

recipes-wpe/wpeframework/wpeframework-plugins_git.bb

Adding missed include files to get snapshot plugin

Snapshot include added into the plugins bb file

---

conf/layer.conf

layer.conf: Mark dunfell (3.1) release compatible

---

recipes-wpe/wpeframework/wpeframework_git.bb

Addressing Ricardo Silva's comments

OCDM Adapter build flag/dependency updates

---

recipes-wpe/wpeframework/include/power.inc

Reason for change: Power Plugin - added flag for controlling persistent state feature.
Test Procedure: Refer ticket
Dependent PR: https://github.com/rdkcentral/ThunderNanoServices/pull/129
Risks: None
Signed-off-by: Arun Madhavan <Arun_Madhavan@comcast.com>

[Power] HP40A-126 : Power plugin persistent state

---

recipes-wpe/wpewebkit/wpewebkit_2.22.bb

Signed-off-by: Peter Griffin <peter.griffin@linaro.org>

wpewebkit_2.22: bump to latest SRCREV

---

recipes-support/rdksplash/rdk-splash-ui_git.bb

Recipe to get RDK-Splash UI to RDK image
rdk-splash-ui: bump to latest
rdk-splashscreen: bump to latest

Cherrypicked rdk-splash-ui from morty to master

---

recipes-wpe/wpeframework/wpeframework_git.bb

Wrong preconditions were set if you use the compositorclient without using the compositor plugin

wpeframework: fix wrong assumption for compositorclient

---

recipes-extended/libcobalt/libcobalt_git.bb

Bump the revision of Cobalt package to use cobalt-21-lts

[cobalt]: bump up to cobalt-21-lts

---

recipes-wpe/wpeframework/wpeframework_git.bb

Please do not merge until confirmation it is ok

Update Thunder to the latest R2 branch

---

recipes-wpe/wpewebkit/wpewebkit_20170728.bb

This reverts commit b6981f9b3bb407a9ba3a2da03d5b22e3d72b7a66.

Tune Webkit browser to pass Widevine waiver tests 

---

recipes-extended/libcobalt/libcobalt_git.bb
recipes-wpe/wpeframework/include/wpeframework.inc
recipes-wpe/wpeframework/wpeframework-clientlibraries_git.bb
recipes-wpe/wpeframework/wpeframework-interfaces_git.bb
recipes-wpe/wpeframework/wpeframework-libraries_git.bb
recipes-wpe/wpeframework/wpeframework-ocdm-clearkey_git.bb
recipes-wpe/wpeframework/wpeframework-ocdm-playready_git.bb
recipes-wpe/wpeframework/wpeframework-ocdm-widevine_git.bb
recipes-wpe/wpeframework/wpeframework-plugins-rdk_git.bb
recipes-wpe/wpeframework/wpeframework-plugins_git.bb
recipes-wpe/wpeframework/wpeframework-ui_git.bb

Changes Include:
Thunder
[Messaging] Improvements
[Tracing] Fix Sys-logging
[SmartLinkType] Avoid a double registration of the notification from SmartClient
[Shell] Add interface to set permission and ownership for volatile/persistent paths
[User:Group]: set persistent/data path permissions/user/group based on the given values
 [JsonRPCLink] Make sure all resources are cleared at destruction.
[SmartInterfaceType] Fix crash at closing process
[PluginActivator] Add PluginActivator utility for systemd integration
[Plugins] Deinitialize on failed Inititalize
[JSON] Parsing error incorrectly set on none quoted simple types.  
[SystemRootPath]Change loader paths to SystemLoaderPaths and use prefix this to generate dynamic library path for systemrootpath enabled plugins
Tools
[Stubgen] Fix …

Align Thunder and Plugins recipes with master
