WebPlatformForEmbedded/meta-wpe

recipes-middleware/webbridge/webbridge_git.bb

Provisioning adds a dependency on dxdrm, which doesn't currently
support MIPS targets.
Signed-off-by: Andre McCurdy <armccurdy@gmail.com>

webbridge: disable provisioning for MIPS builds

---

recipes-wpe/wpe/wpe_0.1.bb

rpi needs it to play MPEG-4 AAC (audio/mpeg) streams

wpe: Add faad gst plugins to rpi rdeps

---

recipes-wpe/wpe/wpe_0.1.bb

Fixes WPE crash when launching html5 with JS

wpe: Build with Thumb2 ISA on RPi

---

recipes-qt/qtbrowser/files/conditional_WebSecurityEnabled.patch
recipes-qt/qtbrowser/qtbrowser_2.0.5.bb

qtbrowser 2.0.5 is the last version known to build relatively cleanly
against upstream qtwebkit 5.4.x (later versions are more dependent on
features found only in the Metrological fork of qtwebkit 5.4.1).

qtbrowser: add recipe for version 2.0.5

---

recipes-qt/qt5/qtwebkit_metro.bb

Up to now the recipe has relied on the distro etc including an
appropriate default set of gstreamer plug-ins. However it's clearer to
make the dependencies explicit (and also conditional on the gstreamer
PACKAGECONFIG option being enabled).

qtwebkit: explicitly define gstreamer1.0 runtime dependencies

---

conf/layer.conf
recipes-core/images/rpi-hwup-image.bbappend

Use rpi-hwup-image as rootfs for bundled initramfs
finally, it will generate Image-initramfs-raspberrypi2.bin
in deploy area which is the single bootable image

images: Enable initramfs image

---

README.md
conf/layer.conf
recipes-core/images/core-image-weston.bbappend
recipes-core/images/wpe-image.bb
recipes-core/images/wpe-image.inc
recipes-core/images/wpe-initramfs-image.bb

Add wpe-image to replace existing latching on to rpi-hwup-image
this image inherits from rpi-basic-image instead which had features
we were enabling in bbappend
secondly, add wpe-initramfs-image for generating a monolithic image
bootable from FAT partition
Keep initramfs bits disabled by default
Adapt core-image-weston to use the new .inc file for including
WPE bits
Document the new imags in README

initramfs-image: Fix build race for initramfs image and add new images

---

recipes-core/images/wpe-image.bb
recipes-core/images/wpe-initramfs-image.bb
recipes-wpe/wpe/wpe_0.1.bb

Makes it optional instead of mandatory to include the rpi image

wpe-image: Use include instead of require for including another image

---

recipes-metrological/webbridge/webbridge_git.bb

Enabling WEBBRIDGE_DEBUG causes optimisation to be set to -O0, which
causes a lot of compiler warnings when building with security cflags
enabled:
|  #  warning _FORTIFY_SOURCE requires compiling with optimization (-O)
|     ^

webbridge: dont enable WEBBRIDGE_DEBUG by default

---

recipes-wpe/wpe/wpe_0.1.bb

Current setting was not getting right packageconfig when
vc4graphics was unset, resulting in wrong backend being
compiled in.

wpe: Set WPE_BACKEND correctly when vc4graphics is disabled

---

recipes-wpe/wpe/wpe_0.1.bb

Usability is severely limited without the platform-plugin package,
so add it as a recommended runtime dependency.

wpe: add wpe-platform-plugin to RRECOMMENDS

---

recipes-wpe/wpe/wpe_0.1.bb

Remove libprovision dependency for hikey as depends on restricted license cppsdk

wpe: disable libprovision for hikey-32 machine

---

recipes-wpe/wpe/wpe_0.1.bb

Adding chrpath-native to EXTRANATIVEPATH (see recent commit) sets up
the PATH to use the OE version of chrpath-native, however a dependency
on chrpath-replacement-native is also required to ensure that the OE
version of chrpath-native is deterministically available.

wpe: add missing dependency on chrpath-replacement-native

---

recipes-core/images/wpe-image.bb
recipes-core/images/wpe-westeros-image.bb

Its smaller in size, moreover openssh daemon does not work well with thumb2 ISA

wpe-image,wpe-westeros-image: use dropbear instead of openssh for sshd

---

recipes-core/base-files/base-files_%.bbappend

**NOTE: this was a build breaking bug present in master, rocko, and pyro, please get it applied to all 3 of those branches**
The intention was clearly to restrict the bbappend customizations to
rpi, not to restrict the whole base-files recipe to only rpi machine...
ERROR: Nothing PROVIDES 'base-files'
base-files was skipped: incompatible with machine $ANYTHING_BUT_RPI (not in COMPATIBLE_MACHINE)
To get the desired result, make the do_install_append() conditional on
rpi platform, rather than setting COMPATIBLE_MACHINE

base-files: restrict bbappend to rpi

---

recipes-wpe/wpewebkit/wpewebkit_20170728.bb

somehow SRCREV begin quote got moved when the BASE_URI in line below
was being updated
typo only seems to appear rocko branch, so fix is only applicable in this branch

wpewebkit: fix SRCREV typo

---

conf/layer.conf

Yocto started to ask for `LAYERSERIES_COMPAT_x` to be explicitly set in 3rd-party layers for compatibility assurance.
This PR fixes the following warning by setting `LAYERSERIES_COMPAT_wpe-layer` to `sumo` in the `master` branch.
WARNING: Layer wpe-layer should set LAYERSERIES_COMPAT_wpe-layer in its conf/layer.conf file to list the core layer names it is compatible with.
The commit in Poky is:
```
commit a0f22fd9712aa724f4e1e9a3ba4a2a9d6ce52403
Author: Richard Purdie <richard.purdie@linuxfoundation.org>
Date:   Fri Apr 6 10:58:48 2018 +0100
bitbake: cookerdata: Issue warning if layer doesn't set LAYERSERIES_COMPAT_x
We'd like layers to set this variable so that we know which layers are compatible
with which others, even if the branch is a generic un-updated "master" branch.
Start …
```

layer.conf: add LAYERSERIES_COMPAT

---

recipes-wpe/wpewebkit/files/0003-Improve-checking-if-libatomic-is-needed-for-armv6-pr.patch
recipes-wpe/wpewebkit/wpewebkit_2.20.bb

After the discussion in #210 , this PR fixes the build issues reported there using two changes:
1. disable the JSC JIT for armv6 processors
2. fix the detection of libatomic in JSC for armv6 processors via a patch
kudos to @kraj for the help debugging this, was difficult !

wpewebkit: fix armv6 build (fixes #210)

---

recipes-wpe/wpebackend-mesa/wpebackend-mesa_0.1.bb
recipes-wpe/wpebackend-rdk/wpebackend-rdk_0.1.bb
recipes-wpe/wpebackend/wpebackend_0.1.bb
recipes-wpe/wpeframework/wpeframework-plugins_git.bb
recipes-wpe/wpeframework/wpeframework-ui_git.bb
recipes-wpe/wpeframework/wpeframework_git.bb
recipes-wpe/wpewebkit/wpewebkit_2.20.bb

Normalize the GitHub SRC_URI of the recipes:
gstreamer1.0-openwebrtc wpebackend-mesa wpebackend-rdk
wpebackend wpeframework-plugins wpeframework-ui wpeframework wpewebkit
for accessing GitHub URIs using standard git protocol. Fixes the following warning:
WARNING: wpeframework-ui-3.0+gitrAUTOINC+c0b3857405-r0 do_fetch:
Failed to fetch URL git://git@github.com/WebPlatformForEmbedded/WPEFrameworkUI.git;protocol=ssh;branch=master,
attempting MIRRORS if available
because of the fetcher trying to use SSH protocol without credentials. We can't assume
everyone has SSH keys configured, so just use the standard git protocol (the default).
Also, there is no need to specify the master branch as this is also a default in the fetcher.

meta-wpe: normalize GitHub SRC_URI in recipes for default protocol/branch

---

tools/manifests/96boards-yocto.xml
tools/manifests/rpi-yocto.xml
tools/rpi-yocto-buildbot.sh

- Switch to using oe-core/bitbake instead of poky
- Fetch OE from github mirrors, just better CDN for all world
- Disable serial console for rpi
- Fix typo in debug-tweaks and enable it
- Add code to run shared state pruning script after build
- Create symlink to reuse common downloads, dont have to download again and again
- Since EGLFS image is build remove wayland from DISTRO_FEATURES too
- Add and enahance debug comments

tools: Fix buildbot job and workspace creation a nit

---

conf/layer.conf

Fixes build error:
ERROR: Nothing PROVIDES 'faad2' (but [...]/gstreamer1.0-plugins-bad_1.14.2.bb DEPENDS on or otherwise requires it)
faad2 was skipped: because it has a restricted license not whitelisted in LICENSE_FLAGS_WHITELIST

faad2 now requires commercial license to be whitelisted

---

recipes-wpe/wpeframework/wpeframework-plugins_git.bb

Commit 129c8c648219 ("wpeframework-plugins: align remote control
changes") changed the PACKAGECONFIG option name for enabling the
'devinput' remote control device from "remote-uinput" to
"remote-devinput".
However, the previous option name "remote-uinput" was left in the
default value for the plugins PACKAGECONFIG, which causes the 'devinput'
device no no longer be enabled by default. Fix this by using the new
name there as well.
Forked from the morty branch, so not tested on other branches.

wpeframework-plugins: Fix 'devinput' in default PACKAGECONFIG

---

recipes-wpe/wpeframework/wpeframework_git.bb

Update wpeframework to 'acec632796c2c27e3f12f0e94ee6843be8d70093',
required to get a rework done in ITVControl. Otherwise causing build
failures on clients of ITVControl that already depend on the new
interface.

wpeframework: Bump to acec632796c2

---

recipes-wpe/wpeframework/wpeframework-ui_git.bb

Avoid forcing the use of ssh protocol for git fetching the
wpeframework-ui sources, as that implies having an ssh key setup in
github, not a reality for all the builders out there.
Instead, use the git protocol, as being done for other WPE framework
related components.

wpeframework-ui: Don't use ssh protocol in git SRC_URI

---

recipes-wpe/wpeframework/wpeframework-ocdm-widevine_git.bb
recipes-wpe/wpeframework/wpeframework-plugin-launcher_git.bb
recipes-wpe/wpeframework/wpeframework-plugins_git.bb
recipes-wpe/wpeframework/wpeframework.inc
recipes-wpe/wpeframework/wpeframework_git.bb

Upstream had a lot of CMAKE refactors, these bump include that with the CMAKE_SYSROOT var in wpeframework.inc. 
Also adds the new WPEFramework Plugin Launcher to launch external services.

Bump to latest and add PluginLauncher

---

recipes-core/packagegroups/packagegroup-wpe-boot.bb

Fixes:
ERROR: onemw/meta-wpe/recipes-core/packagegroups/packagegroup-wpe-boot.bb: This recipe does not have the LICENSE field set (packagegroup-wpe-boot)      | ETA:  00:00:21
ERROR: Failed to parse recipe: onemw/onemw/oe-builds/svp-1/onemw/meta-wpe/recipes-core/packagegroups/packagegroup-wpe-boot.bb

add missing LICENSE tag

---

conf/layer.conf
recipes-wpe/wpebackend-fdo/wpebackend-fdo_git.bb

Fixes
do_package_qa: QA Issue: non -dev/-dbg/nativesdk- package contains symlink .so: wpebackend-fdo path '/work/core2-64-yoe-linux-musl/wpebackend-fdo/1.0.0+gitAUTOINC+5a4b58c7d6-r0/packages-split/wpebackend-fdo/usr/lib/libWPEBackend-fdo-0.1.so' [dev-so]

wpebackend-fdo: Fix packaging dev-so QA issue and fix Warrior compatibilty

---

recipes-graphics/libepoxy/libepoxy_%.bbappend

to resolve (Couldn't open "/usr/lib/libEGL.so.1": "/usr/lib/libEGL.so.1": cannot open shared object file: No such file or directory)
error in WPEFramework.
Signed-off-by: rkhan467 <Riyaz.l@ltts.com>

libepoxy: Removing double quotes from graphics lib path

---

recipes-graphics/westeros/westeros-soc-drm.bb

- westeros-gl drm added v4l2 support for rpi with
a macro enabled with old code.
Ref. https://github.com/rdkcmf/westeros/commit/9f597624c850923bfa51d3a74b33f17ad79b2ecf
Signed-off-by: Moorthy Baskar <moorthy.baskaravenkatraman-sambamoorthy@linaro.org>

westeros-soc-drm: CFLAGS as per the new drm code

---

recipes-wpe/libwpe/libwpe_0.2.bb

Debug information should not be removed as it prevents from
getting meaningful callstacks.
Note: Yocto handles debug information by itself appropriately
(e.g. stripping it in a final image if instructed to do so).
Signed-off-by: Damian Wrobel <dwrobel@ertelnet.rybnik.pl>

Do not remove debug information.

---

recipes-wpe/wpeframework/wpeframework-ocdm-widevine_git.bb

to fix the breakage due to wpeframework CDM interface updates

wpeframework-ocdm-widevine: bump to latest

---

recipes-multimedia/gstreamer/gstreamer1.0/0002-Small-robustness-fixes.patch

Makes devtool happy
WARNING: gstreamer1.0-1.16.0-r0 do_patch: Fuzz detected:
Applying patch 0002-Small-robustness-fixes.patch
patching file gst/gststructure.c
patching file libs/gst/base/gstadapter.c
Hunk #1 succeeded at 227 with fuzz 2 (offset 2 lines).
The context lines in the patches can be updated with devtool:

gstreamer1.0: Refresh 0002-Small-robustness-fixes.patch

---

recipes-graphics/westeros/files/0004-Dispatch-custom-queue-instead-flushing-display.patch
recipes-graphics/westeros/westeros-sink.bb
recipes-graphics/westeros/westeros-soc-drm.bb
recipes-graphics/westeros/westeros.inc

westeros-sink	: Removing the patch which is already part of the code
westeros-soc-drm: Use DRM_USE_NATIVE_FENCE instead of DRM_NO_NATIVE_FENCE to resolve build issues
to exclude Mesa EGL API's which are not exposed.
westeros.inc	: Updating the revision
Signed-off-by: Khan3033 <Riyaz.l@ltts.com>

westeros	: Rebasing the patch

---

recipes-graphics/westeros/westeros-soc-drm.bb

some API's of mesa which are not supposed to be available.
Signed-off-by: Khan3033 <Riyaz.l@ltts.com>

westeros-soc-drm: Add -DDRM_NO_NATIVE_FENCE for rpi/vc4 to disable

---

recipes-multimedia/gstreamer/gstreamer1.0-plugins-good/0006-Manual-revert-of-bfd0e022-qtdemux-rework-segment-eve.patch

The patch no longer applies cleanly which breaks the build.
Signed-off-by: Peter Griffin <peter.griffin@linaro.org>

gstreamer1.0-plugins-good: update 0006 to apply cleanly on v1.16.1

---

recipes-support/libsoup/libsoup-2.4_2.58.1.bbappend

Reason for change: remove patch for version as its already part of the code
Test Procedure: Build and verify.
Risks: Low.
Signed-off-by: rkhan467 <Riyaz.l@ltts.com>

remove patch for version as its already part of the code for dunfell migration

---

recipes-graphics/userland/files/0020-brcmEGL-wayland-support.patch
recipes-graphics/userland/userland_%.bbappend

In wayland package enabled case, brcmEGL lib use wayland call so this library has to be linked with wayland libraries to avoid undefined symbol issue

Userland: link libbrcmEGL with wayland libraries while wayland support enabled case

---

recipes-extended/libcobalt/libcobalt_git.bb

This fixes the build error:
| build-raspberrypi-rdk-hybrid-thunder/tmp/work/cortexa7t2hf-neon-vfpv4-rdk-linux-gnueabi/wpeframework-plugins/3.0+gitrAUTOINC+e0b75be2b6-r1/git/Cobalt/CobaltImplementation.cpp:5:30: fatal error: starboard/export.h: No such file or directory
|  #include starboard/export.h
|                               ^
| compilation terminated.
| make[2]: *** [Cobalt/CMakeFiles/WPEFrameworkCobalt.dir/CobaltImplementation.cpp.o] Error 1
Signed-off-by: Simon Chung <simon.c.chung@accenture.com>

Fix build errors when using sstate cache

---

recipes-extended/libcobalt/libcobalt_git.bb
recipes-graphics/wayland-egl-bnxs/files/wayland-egl-bnxs-nxjoin.patch
recipes-graphics/wayland-egl-bnxs/wayland-egl-bnxs_git.bbappend
recipes-wpe/wpeframework/include/cobalt.inc
recipes-wpe/wpeframework/wpeframework-plugins/0007-Cobalt-resolution-param-configurable.patch
recipes-wpe/wpeframework/wpeframework-plugins_git.bb

Cobalt is crashing, if wl_egl_window_create is invoked first, since it is not registered with NXClient. So added changes to register with NxClient using NxClient_Join

Cobalt: fix to work in broadcom platform

---

recipes-wpe/wpeframework/wpeframework_git.bb

The distro features are a mess and should be reworked. They blend in machine features and distro features and we should re-organise them properly based on Broadcom's availability of SVP. 
This is a temp hack to decouple opencdm_gst if playready_nexus_svp is enabled.

wpeframework: hack decouple opencdm_gst

---

recipes-wpe/wpeframework/wpeframework_git.bb

Fixes issue where init.d can't start WPEFramework during bootup on sysinit bootsystems.

wpeframework: fix initd permission of start script

---

recipes-multimedia/libopus/libopus%.bbappend

It adds .bbappend file for meta-openembedded/meta-oe/recipes-multimedia/libopus recipe.
NE10 provides optimized routines for math / signal processing for ARM CPUs.
However it produces audio noise when OPUS audio codec is used with YouTube video in Cobalt browser.
NE10 library is not used in buildroot.
This change is verified for RPI and Amlogic platform.

Removed NE10 library dependency for libopus.

---

recipes-wpe/wpeframework/include/webkitbrowser.inc
recipes-wpe/wpeframework/wpeframework-plugins_git.bb

Removing YouTube, as that is superceded with Cobalt
Adding Apps, as an extra app instance

wpeframework-plugins: cleanup webkit plugins

---

conf/layer.conf

Now westeros is working with vc4graphics wayland enable so, okay to have compositor plugin / package config
Signed-off-by: Moorthy Baskar <moorthy.bs@ltts.com>

layer.conf: enable compositor distro for vc4graphics

---

recipes-wpe/wpeframework/wpeframework-plugins_git.bb
recipes-wpe/wpeframework/wpeframework-tools-native_git.bb
recipes-wpe/wpeframework/wpeframework-ui_git.bb
recipes-wpe/wpeframework/wpeframework_git.bb

Points to rdkcentral layer instead of WebPlatformForEmbedded layer for Thunder, ThunderUI and ThunderNanoservice components.
Signed-off-by: KrishnakumarPathivuraj <krishnakumar.pathivuraj@ltts.com>

Updated SRC_URI for Thunder, ThunderUI and ThunderNanoServices

---

recipes-core/systemd/systemd_%.bbappend

https://jira.rdkcentral.com/jira/browse/HP40A-326: Based on this issue, found that in some router case, it is sending ARP request to device for the validation of IPs. So in that case os stack is responding on this with details. But if both eth0 and wlan0 are up, then it will share the same details with both interface with its own MAC address. This making conflict with router, and it will issue new IP. So adding using arp_ignore = 1 to avoid this situation and respond only for its own request.

Set Arp ignore rules to avoid arp replay for all other interfaces

---

classes/wpe-sidecar-image.bbclass

This commit introduces a sidecar `.bbclass` recipe, which creates a deployment package containing only selected libraries / binaries.
The binary selection process happens via appending / overloading the `WPE_SIDECAR_FILENAMES_TO_COPY` bb variable.

Create sidecar image class

---

linter/linter.out
recipes-wpe/wpewebkit/wpewebkit.inc

The `PYTHON_EXECUTABLE` variable is exported by the `pythonnative` class, but not `python3native` which causes a configuration error while building with python3-native.

Fix bad variable pass for python executable

---

linter/linter.out
recipes-wpe/libwpe/libwpe_1.0.0.bb
recipes-wpe/wpebackend-fdo/wpebackend-fdo_git.bb
recipes-wpe/wpebackend-mesa/wpebackend-mesa_0.1.bb
recipes-wpe/wpebackend-rdk/wpebackend-rdk_git.bb
recipes-wpe/wpeframework/include/wpeframework.inc
recipes-wpe/wpeframework/wpeframework-clientlibraries_git.bb
recipes-wpe/wpeframework/wpeframework-interfaces_git.bb
recipes-wpe/wpeframework/wpeframework-ocdm-clearkey_git.bb
recipes-wpe/wpeframework/wpeframework-ocdm-playready-nexus-svp_git.bb
recipes-wpe/wpeframework/wpeframework-ocdm-playready-nexus_git.bb
recipes-wpe/wpeframework/wpeframework-ocdm-playready_2.5+git.bb
recipes-wpe/wpeframework/wpeframework-ocdm-playready_4.0+git.bb
recipes-wpe/wpeframework/wpeframework-ocdm-playready_git.bb
recipes-wpe/wpeframework/wpeframework-ocdm-widevine-nexus-svp_git.bb
recipes-wpe/wpeframework/wpeframework-ocdm-widevine_git.bb
recipes-wpe/wpeframework/wpeframework-plugin-launcher_git.bb
recipes-wpe/wpeframework/wpeframework-plugins-rdk_git.bb
recipes-wpe/wpeframework/wpeframework-plugins_git.bb
recipes-wpe/wpeframework/wpeframework-rdkservices_git.bb
recipes-wpe/wpeframework/wpeframework-ui_git.bb
recipes-wpe/wpewebkit/wpewebkit_2.22.bb
recipes-wpe/wpewebkit/wpewebkit_2.28.bb
recipes-wpe/wpewebkit/wpewebkit_2.30.bb
recipes-wpe/wpewebkit/wpewebkit_20170728.bb

This commit introduce variables that are easier to override from outside
of the recipe. This way the version handling is improved.
Changes:
* RECIPE_BRANCH variable - use instead of hardcoded branch name
* All SRCREVS are at least a weak assignments

Changes improving version handling for wpe* recipes

---

recipes-multimedia/cenc/gstreamer1.0-plugins-cencdecrypt_git.bb
recipes-wpe/wpeframework/include/wpeframework-common.inc
recipes-wpe/wpeframework/include/wpeframework-plugins-rdk.inc
recipes-wpe/wpeframework/include/wpeframework.inc
recipes-wpe/wpeframework/wpeframework-clientlibraries_git.bb
recipes-wpe/wpeframework/wpeframework-interfaces_git.bb
recipes-wpe/wpeframework/wpeframework-libraries_git.bb
recipes-wpe/wpeframework/wpeframework-ocdm-playready_4.0+git.bb
recipes-wpe/wpeframework/wpeframework-plugins-rdk_git.bb
recipes-wpe/wpeframework/wpeframework-plugins_git.bb
recipes-wpe/wpeframework/wpeframework_git.bb

Changes include 
Thunder:
[StubGen] 
Use qualified call to the Invoke method, Forward declare IShell and ISubSystem enums and Support pointer to const interface as output parameter
[JsonGen]
Support cross-reference from JSON meta to C++ header 
JSON-RPC spec compliance and Generate version information code 
[CMake] 
New Config generator support and switch off legacy config generator
[HELLGRIND] 
Address the issues reported by Hellgrind
[Core] Fix also the admin file of the SharedBuffer
Enhance the Callstack handling reporting.
Make sure the framework automatically accepts auto generated versioning calls.
Warning option enhancement and expose the plugin Search path and the System path from thunder config
ThunderNanoServices & ThunderNanoServicesRDK
Moving PlayerInfo and DeviceInfo to …

Align Thunder and Plugins recipes with master
